// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using lesson65.Models;

#nullable disable

namespace lesson65.Migrations
{
    [DbContext(typeof(CountryDb))]
    partial class CountryDbModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("lesson65.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Area")
                        .HasColumnType("integer");

                    b.Property<string>("Capital")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OfficialName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Population")
                        .HasColumnType("integer");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Area = 200000,
                            Capital = "Bishkek",
                            Name = "Kyrgyzstan",
                            OfficialName = "The Kyrgyz Republic",
                            Population = 8000000,
                            Region = "Asia"
                        },
                        new
                        {
                            Id = 2,
                            Area = 9833520,
                            Capital = "Washington",
                            Name = "USA",
                            OfficialName = "United States of America",
                            Population = 330000000,
                            Region = "North America"
                        },
                        new
                        {
                            Id = 3,
                            Area = 17000000,
                            Capital = "Moscow",
                            Name = "Russia",
                            OfficialName = "Russian Federation",
                            Population = 150000000,
                            Region = "Europe and Asia"
                        },
                        new
                        {
                            Id = 4,
                            Area = 92212,
                            Capital = "Lisbon",
                            Name = "Portugal",
                            OfficialName = "The Portuguese Republic",
                            Population = 10200000,
                            Region = "Europe"
                        },
                        new
                        {
                            Id = 5,
                            Area = 9984670,
                            Capital = "Ottawa",
                            Name = "Canada",
                            OfficialName = "Dominion of Canada",
                            Population = 38000000,
                            Region = "Europe"
                        },
                        new
                        {
                            Id = 6,
                            Area = 357592,
                            Capital = "Berlin",
                            Name = "Germany",
                            OfficialName = "Federal Republic of Germany",
                            Population = 83800000,
                            Region = "Europe"
                        },
                        new
                        {
                            Id = 7,
                            Area = 551695,
                            Capital = "Paris",
                            Name = "France",
                            OfficialName = "The French Republic",
                            Population = 68000000,
                            Region = "Europe"
                        },
                        new
                        {
                            Id = 8,
                            Area = 209331,
                            Capital = "London",
                            Name = "Great Britain",
                            OfficialName = "The United Kingdom of Great Britain and Northern Ireland",
                            Population = 67000000,
                            Region = "Europe"
                        },
                        new
                        {
                            Id = 9,
                            Area = 41285,
                            Capital = "Bern",
                            Name = "Switzerland",
                            OfficialName = "Swiss Confederation",
                            Population = 8700000,
                            Region = "Europe"
                        },
                        new
                        {
                            Id = 10,
                            Area = 385207,
                            Capital = "Oslo",
                            Name = "Norway",
                            OfficialName = "The Kingdom of Norway",
                            Population = 5500000,
                            Region = "Europe"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
